{% set name = "pulseaudio" %}
{% set version = "14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-{{ version }}.tar.xz
  sha256: a834775d9382b055504e5ee7625dc50768daac29329531deb6597bf05e06c261

build:
  number: 10
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('pulseaudio', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - make
    - pkg-config
  host:
    - alsa-lib
    - alsa-lib >=1.0.19
    - libsndfile
    - libsndfile >=1.0.18
    - libatomic_ops
    - libatomic_ops >=1.2
    - libtool
    - libtool >=2.4
    # X11 (optional)
    - libcap
    - glib
    - glib >=2.0
    # GTK+ 3.0 (optional)
    # Avahi (optional)
    - jack
    # libasyncns (optional)
    # tcpwrap (optional)
    # lirc (optional)
    # Gconf 2.0 (optional as of 0.9.12)
    - dbus
    - dbus >=1.4.12
    - fftw
    - fftw >=3.0
    # libgdbm (mandatory from 0.9.11 to 0.9.15, optional as of 0.9.16)
    # libtdb (optional as of 0.9.16)
    - check
    # sbc (>= 1.0, optional)
    # libsystemd-login (optional)
    # libsystemd-journal (optional)
    # libbluetooth (optional)
    - perl-xml-parser
    - libiconv
    - openssl
    - libudev
  run:
    - libtool >=2.4


test:
  commands:
    - test -f ${PREFIX}/lib/libpulse.so

about:
  home: https://www.freedesktop.org/wiki/Software/PulseAudio/
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: LGPL
  summary: A networked sound server
  doc_url: https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/

extra:
  recipe-maintainers:
    - andfoy
    - ryanvolz
    - scopatz
